### ISSUE TITLE
Where did the documentation go?

### ISSUE THREAD

**Issue by alessandrojcm** [fauna/faunadb-python#148]
Hi there!

The title sums it up pretty much, why is the readthedocs page not working? I'm having a hard time trying to find info about the driver.

**Comment by trevorsibanda** [comment]
Hi @alessandrojcm we pulled the page and have a high priority ticket to update the documentation and get the page available again.

Apologies for the inconvenience.

In the meantime, you can use the FQL API reference for guidance, https://app.fauna.com/documentation/reference/queryapi

**Comment by chrisvaughan83** [comment]
any update on this? the page is still down.

**Comment by n400** [comment]
checking into this

**Comment by sharypovandrey** [comment]
+

**Comment by tedmiston** [comment]
The FQL API docs are a useful reference but not having the Python driver docs available makes it pretty cumbersome to use.

**Comment by n400** [comment]
This is now being tracked internally as DRV-317 (which is not publicly available, but will make it easier to check in on its status in the future). We're all-hands-on-deck with the next release right now, but will have someone look into this right after that. Thank you for understanding.

**Comment by Curiouspaul1** [comment]
any update on the docs yet.. is someone looking intoo it already??

**Comment by trevorsibanda** [comment]
@Curiouspaul1 you might find http://fauna.github.io/faunadb-python/ and http://fauna.github.io/faunadb-python/api/ useful in the mean time.

**Comment by Curiouspaul1** [comment]
> @Curiouspaul1 you might find http://fauna.github.io/faunadb-python/ and http://fauna.github.io/faunadb-python/api/ useful in the mean time.

Thanks a lot this is helpful

**Comment by n400** [comment]
Closing this issue as we have replaced ReadtheDocs with GH Docs (http://fauna.github.io/faunadb-python/ and http://fauna.github.io/faunadb-python/api/). 

But please let us know if this is insufficient for any reason!
