### ISSUE TITLE
why raising errors?

### ISSUE THREAD

**Issue by Catastropha** [fauna/faunadb-python#157]
Why raising errors on not found? you need try-catch on every query - very ugly

**Comment by Catastropha** [comment]
found in the docs where it says to use exists predicate, but it returns boolean which makes you do more requests...

**Comment by marrony** [comment]
no, you can do everything in a single query

**Comment by Catastropha** [comment]
can you please explain? Really appreciate it!

**Comment by marrony** [comment]
```python
client.query(
   q.if_(
      q.exists(ref),
      q.get(ref),
      q.create(....)
   )
)
```
everything will be executed in a single query/transaction

**Comment by Catastropha** [comment]
@marrony can you please help me with an example on how would you search documents by a string field that contain a specific substring? and paginate over the results? 

I've found ContainStr but I don't know how to use it for this purpose. Your help will be very much appreciated.

**Comment by marrony** [comment]
we have many different answer to that question in our forum https://forums.fauna.com, or you can join our Community Slack on fauna-community.slack.com
