### ISSUE TITLE
version 4.0.0 of the driver is not stable

### ISSUE THREAD

**Issue by LordGhostX** [fauna/faunadb-python#171]
The version 4.0.0 of the python faunadb driver has an error which needs to be resolved. While trying to run the sample code you'll get an error which says "ModuleNotFoundError: No module named 'faunadb.streams'" but this is not present on the 3.0.0 of the python driver

<img width="568" alt="Screenshot 2020-11-19 at 1 16 51 AM" src="https://user-images.githubusercontent.com/47832826/99604045-e8dd8700-2a04-11eb-86b1-8fa62f9b7973.png">

**Comment by nathaniel-may** [comment]
@LordGhostX - Thank you for bringing this to our attention. We are looking into it.

**Comment by trevorsibanda** [comment]
Fixed in v4.0.1. @LordGhostX can you confirm that its working for you. If the problem persists feel free to reopen this ticket. 

#172
