### ISSUE TITLE
Example Documentation for Lambdas

### ISSUE THREAD

**Issue by asencis** [fauna/faunadb-python#175]
Please could we have some examples of using Lambda() FQL with this library? 

I can't seem to find anything in the documentation...

**Comment by faunaee** [comment]
@asencis Did you see the reference page for the `Lambda` function?
https://docs.fauna.com/fauna/current/api/fql/functions/lambda?lang=python

`Lambda` is equivalent to an anonymous function, which allows you to perform operations, using FQL functions, within the `Lambda` function.

If you can tell me a bit about what you are trying to accomplish, I can provide a specific example.

**Comment by asencis** [comment]
@faunaee Hi Ewan, thanks for your reply. Let's say I wanted to bulk create records. I attempted a loop create:

```
# for row in data:
    #     result = client.query(
    #         q.create(
    #             q.collection(collection_name),
    #             {
    #                 "data": row
    #             }
    #         )
    #     )
```

This worked, but for 100000 rows - is completely impractical. I'm perhaps bending FaunaDB to our whim, but how could a `Lambda()` work for this scenario? We have `q.lamda_` but also pythons inbuilt `lambda` expressions...which do we use when and where? It's just not clear.

**Comment by faunaee** [comment]
Provided that your data fits within Fauna's query limits: https://docs.fauna.com/fauna/current/api/fql/documents#limits
you can send your data within the query and have multiple documents created in a single transaction.

There's an example in the Indexing tutorial that shows creating one document per alphabet letter:
https://docs.fauna.com/fauna/current/api/fql/documents#limits

That example uses the `Map` function to iterate over the provided array of document data, and the contents of the `Lambda`, which is called for each iteration, creates the appropriate document.

Fauna's Python driver uses `q.lambda_` to make it distinct from Python's built in `lambda` function. You use `q.lambda_` when you want to execute one or more FQL functions, likely repeatedly (such as within `Map`), within your Fauna database. You'd used Python's `lambda` function when you want to execute logic locally, likely repeatedly.

You can combine the two: if you have multiple transactions to run, you might use `lambda` to iterate through your workload to compose and execute queries involving `q.lambda_`.

If it helps, FQL lets you run logic within your Fauna database, which can perform read and write operations without incurring additional network traffic, such as your example where you are making one request per document. Sometimes, one transaction per document is unavoidable, but it all depends on how you want to solve the problem that you are trying to address.

**Comment by brianraila** [comment]
> @faunaee Hi Ewan, thanks for your reply. Let's say I wanted to bulk create records. I attempted a loop create:
> 
> ```
> # for row in data:
>     #     result = client.query(
>     #         q.create(
>     #             q.collection(collection_name),
>     #             {
>     #                 "data": row
>     #             }
>     #         )
>     #     )
> ```
> 
> This worked, but for 100000 rows - is completely impractical. I'm perhaps bending FaunaDB to our whim, but how could a `Lambda()` work for this scenario? We have `q.lamda_` but also pythons inbuilt `lambda` expressions...which do we use when and where? It's just not clear.

@asencis  When reading data from a collection or index you can use the built in lambda function as below.

```
data = client.query( 
              # Maps over an array or FQL page and calls an expression/lambda on each item.
              # In this case, we are calling q.get on each item returned from the 2nd parameter’s q.paginate.
               q.map_(
                   # q.get takes a document’s Ref and retrieves the entire document.
                   # Refs are similar to primary/foreign keys and serve as unique pointers to documents.
                   # q.index returns the Ref for an index. Note that all entities in FaunaDB are documents and have Refs.
                   # q.match takes the ref of an index, along with search parameters, and returns something called a SetRef.
                   # Finally, q.paginate takes a SetRef and returns a page with iterable data.
                   lambda x: q.get(x),
                   q.paginate(q.match(
                       q.index("products_by_category"), category)))   
                   )

```

**Comment by fireridlle** [comment]
@asencis  You usually don't need to call `q.lambda_` directly as lambdas in queries will be converted for you.
Both approaches are correct
```
data = [
        {"name": "Phones"},
        {"name": "Laptops"},
        {"name": "Watches"},
        {"name": "Apple"}
  ]
client.query(q.map_(
        lambda row: q.create(q.collection(collection_name), {"data": row}),
        data
    ))
    
client.query(q.map_(
        q.lambda_("row", q.create(q.collection('users'), {"data": {"name": "Phones"}})),
        data
))

```
