### ISSUE TITLE
Get query read/write/... metrics

### ISSUE THREAD

**Issue by MaximeWeyl** [fauna/faunadb-python#235]
The doc says that metrics are found in the http headers.
However, this lib does not seam to expose them.
It would be nice.

**Comment by faunaee** [comment]
Query metrics, and other response headers, are available via the observer callback: https://github.com/fauna/faunadb-python/blob/v4/faunadb/client.py#L190-L191

It is, indeed, not well documented. Here's an example that demonstrates its use:

```
#!/usr/bin/env python3
"""
A Python client example.
"""
from faunadb import query as q
from faunadb.client import FaunaClient
from faunadb.errors import FaunaError

def observe(response):
  h = response.response_headers

  print('bytesIn:', h["x-query-bytes-in"])
  print('bytesOut:', h["x-query-bytes-out"])
  print('queryTime:', h["x-query-time"])
  print('readOps:', h["x-byte-read-ops"])
  print('writeOps:', h["x-byte-write-ops"])
  print('readBytes:', h["x-storage-bytes-read"])
  print('writeBytes:', h["x-storage-bytes-write"])
  print('retries:', h["x-txn-retries"])

# You'd setup a client like this when using Fauna Dev
client = FaunaClient(
  secret="secret",
  domain="localhost",
  scheme="http",
  port=8443,
  observer=observe
)

try:
  result = client.query(
    q.do(
      q.create_collection({ "name": "_" }),
      q.abort("Abort!")
    )
  )
except FaunaError as err:
  print("err: ", err)
else:
  print(result)
```

The result should be similar to:

```
$ python3 test.py 
bytesIn: 73
bytesOut: 262
queryTime: 8
readOps: 0
writeOps: 0
readBytes: 0
writeBytes: 0
retries: 0
err:  ErrorData(code='validation failed', description='document data is not valid.', position=['do', 0, 'create_collection'], failures=[Failure(code='reserved name', description='Invalid name _. Reserved names: sets, _, events, self, instances.', field=['name'])])
```

**Comment by MaximeWeyl** [comment]
Thank you Ewan

**Comment by doom-weaver** [comment]
Hey @MaximeWeyl,

Please note that as only a subset of these metrics (`x-byte-read-ops`, `x-byte-write-ops`, `x-compute-ops`) will be reflected in any billing you incur, documented here:

https://docs.fauna.com/fauna/current/learn/understanding/billing#perquery

I've cut this pull request: https://github.com/fauna/faunadb-python/pull/236 to get metrics observation called out in the README.

I'm going to resolve this for now. Please reopen if you have further questions.
