### ISSUE TITLE
Fauna version upgrade message provides invalid link

### ISSUE THREAD

**Issue by ryancausey** [fauna/faunadb-python#248]
When interactively messing around with the faunadb python client, it appears to check if a new version is available. However, the chanelog URL pointed to by the upgrade message is invalid and results in a 404.

Reproduction steps:

1. install an old version of the faunadb python client in your local environment
2. drop into a python REPL
3. instantiate the faunadb python client

Expected result:

A valid changelog link is provided, I.E. https://github.com/fauna/faunadb-python/blob/v4/CHANGELOG.md

Actual result:

An invalid changelog link is provided: https://github.com/fauna/faunadb-python/blob/main/CHANGELOG.md

```python
>>> from faunadb.client import FaunaClient
>>> fauna_client = FaunaClient(secret="super_secret_key", domain="db.us.fauna.com", timeout=5)
+--------------------------------------------------------------------------------+
| New fauna version available 4.2.0 => 4.3.0                                     |
| Changelog: https://github.com/fauna/faunadb-python/blob/main/CHANGELOG.md      |
+--------------------------------------------------------------------------------+
>>>
```

**Comment by henryfauna** [comment]
Thanks for bringing this up! Should be fixed by https://github.com/fauna/faunadb-python/pull/249 and will get rolled into a subsequent release.
