### ISSUE TITLE
query.object should take a dict in addition to kvargs

### ISSUE THREAD

**Issue by eaceaser** [fauna/faunadb-python#40]
to make it consistent with the behavior of .quote, of which it is a counterpart

**Comment by andy-faunadb** [comment]
Maybe it should just take a dict instead? `def object(dct, **kwargs)` is ambiguous for `object(dct={"a": 1})`. (Is it `{"a": 1}` or `{"dct": {"a": 1}}`?) We could just use a really unusual name for the first argument, but consistently taking a dict makes the most sense to me.

**Comment by eaceaser** [comment]
i support that approach

**Comment by freels** [comment]
what does a kvargs call currently look like?

**Comment by eaceaser** [comment]
object(key1=value1, key2=value2)

as opposed to object({key1: value1, key2: value2})

**Comment by freels** [comment]
quote and object are not really counterparts. object is better thought of as a constructor... what's the use-case for passing a dict directly to it?

**Comment by andy-faunadb** [comment]
They're just different syntaxes. Kwargs notation makes it more difficult to have variable keys but it can be done with `query.object(**{key: val})`.

**Comment by eaceaser** [comment]
If I have a helper method to create some sort of structure, for example,
you have to jump through hoops to pass it in through dynamic arguments.

**Comment by freels** [comment]
does splatting them out work?

**Comment by eaceaser** [comment]
i disagree that they aren't counterparts, in practice.

both return an object literal, but one escapes the entire object, whereas the other allows for language parsing of child nodes.

**Comment by freels** [comment]
quote does not return an object literal if you do not pass an object.

**Comment by eaceaser** [comment]
in the use case of quoting an object it does

**Comment by eaceaser** [comment]
also, the object() notation in this case is not a constructor; its a helper to create the query language construct.

This does not represent an object type in our client.

**Comment by freels** [comment]
but that's a specific case, not a fact of general behavior. `object` is meant to be a value constructor.

**Comment by freels** [comment]
it is for the purposes of writing out query expressions however, is it not?

**Comment by eaceaser** [comment]
yeah, but in practice, that is how people are going to be using these methods; having one take a dict and the other require splatting the dict is very strange

**Comment by freels** [comment]
I disagree. it's a false equivalence to make them behave similarly.

**Comment by eaceaser** [comment]
its kind of a moot point, because we have to make them behave similarly in every single other language that doesn't support dynamic argument keys anyways.

i think forcing users to use an esoteric language feature (which splatted dynamic arguments are) in order to satisfy an abstraction that users will rarely be aware of is the wrong approach.

From the perspective of the user, they're both going to be dictionaries of arbitrary keys and values. The only difference is that, in the latter case, interpretation of leaves is necessary. Needing to force the user to remember two function syntaxes when both objects are the same data type to the user, is not obvious, and not mirrored by any other client anyways.

**Comment by freels** [comment]
Is splatting args that esoteric in python? IME you use it all the time in ruby and scala.

> From the perspective of the user, they're both going to be dictionaries of arbitrary keys and values. The only difference is that, in the latter case, interpretation of leaves is necessary. 

This difference has been an extreme source of confusion already. In impoverished JSON they seem similar, but in terms of fauna's query language semantics, they are very different: One is used to quote an arbitrary expression to make it a literal. the other is used to construct an object. Describing them as "one quotes the whole tree and one quotes only a single level" is inaccurate.

> Needing to force the user to remember two function syntaxes when both objects are the same data type to the user, is not obvious, and not mirrored by any other client anyways.

Alternatively, two syntaxes do a better job of differentiating the functions for different use-cases.

**Comment by eaceaser** [comment]
if you feel strongly about this then its fine;

I just think that, as a user, especially one following our docs and examples, moving from quoting a dictionary literal to to splatting into an object constructor is non-obvious, regardless of the theoretical underpinnings. 

I don't think users will look at this and thank us for enlightening them, I think that they'll be upset that, to them, the syntax is inexplicably different.

**Comment by freels** [comment]
I feel strongly about it, but so do you, so I think it's a good discussion. :)

Whatever else is true, the docs and clients should be on the same page in terms of semantics and message. In the API docs, we say that "`object` constructs an Object with the provided fields and values", and "`quote` returns the unevaluated form of an expr."

How often are users going write out query expressions? What makes you say that a dynamic set of fields is the most common use case? Would this be replaced by translation by a model layer in a larger app?

**Comment by n400** [comment]
closing this as old because I don't think the Python driver has query.object
