### ISSUE TITLE
Client cleanup of requests session needs work

### ISSUE THREAD

**Issue by ashfire908** [fauna/faunadb-python#81]
Right now it's just a blind call to `self.session.close()` on `Client.__del__`. This should be handled better.

**Comment by andy-faunadb** [comment]
Running tests in python3, I get this warning several times when I run tests: `ResourceWarning: unclosed <socket.socket fd=6, family=AddressFamily.AF_INET, type=SocketKind.SOCK_STREAM, proto=6, laddr=('127.0.0.1', 53055), raddr=('127.0.0.1', 8443)>`
